## Atividades em NuPy

Observação: As atividades mencionadas foram encontradas no repositório do GitHub em https://github.com/infoslack/ml-book-exemplos. Essas atividades são baseadas no livro 'Entendendo Machine Learning com Scikit-Learn e TensorFlow na prática'. Você pode acessar o conteúdo do livro no seguinte link: https://infoslack.pro/ml-book/contents/pandas-exercicios.html. Créditos ao autor e ao repositório mencionado.

In [1]:
# Importe o numpy, utilize a abreviação 'np'

In [1]:
import numpy as np

In [2]:
# Utilizando np.array() crie:
# 1 array unidimensional "vetor"
# 1 array de duas dimensões "matrix"
# 1 array de três dimensões

In [5]:
# 1 array unidimensional "vetor"
arr1 = np.array([1,2,3,4])

In [6]:
print(arr1)

[1 2 3 4]


In [94]:
# 1 array de duas dimensões "matrix"
arr2 = np.array(
[
    [1,2],
    [3,4],
    [5,6]
])

In [95]:
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
# 1 array de três dimensões
arr3 = np.array(
[
    [[1,2,3,4,5]],
    [[6,7,8,9,10]],
    [[11,12,13,14,15]]
])

In [19]:
print(arr3)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


In [3]:
# Liste os atributos de todos os arrays criados anteriormente
# número de dimensões, tipo de dado, tamanho

In [33]:
#arr1
print(arr1.ndim)
print(type(arr1))
print(arr1.size)

1
<class 'numpy.ndarray'>
4


In [96]:
#arr2
print(arr2.ndim)
print(type(arr2))
print(arr2.size)

2
<class 'numpy.ndarray'>
6


In [35]:
#arr3
print(arr3.ndim)
print(type(arr3))
print(arr3.size)

3
<class 'numpy.ndarray'>
15


In [38]:
# Crie um array de números 1 de shape (10, 2)
arr4 = np.ones((10,2))

In [39]:
print(arr4)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
# Crie um array de zeros de shape (5, 4, 3)
arr5 = np.zeros((5,4,3))

In [41]:
print(arr5)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [42]:
# Crie um array com um range entre 0 e 100 e com step 3
arr6 = np.arange(0,100,3)

In [43]:
print(arr6)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [44]:
# Crie um array random (com elementos aleatórios) entre 0 e 10 de tamanho (7, 2)
arr7 = np.random.randint(10, size=(7,2))

In [45]:
print(arr7)

[[9 4]
 [5 0]
 [4 1]
 [6 6]
 [2 4]
 [6 7]
 [8 1]]


In [47]:
# Crie um array random float com elementos entre 0 e 1 com shape (5, 3)
arr8 =  np.random.random(size=(5,3))

In [48]:
print(arr8)

[[0.46368465 0.83337863 0.41502034]
 [0.09044228 0.17602942 0.01226922]
 [0.55046785 0.36076604 0.93438462]
 [0.16196953 0.03977353 0.24237069]
 [0.77758644 0.12392575 0.18956501]]


In [49]:
# Utilize  o seed com valor 42 e crie um array de números aleatórios entre 0 e 10 de tamanho (5, 3)
np.random.seed(42)
arr9 = np.random.randint(10, size=(5,3))


In [50]:
print(arr9)

[[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]
 [7 2 5]]


In [55]:
# Selecione o primeiro elemento do último array que você criou
arr9[0,0]

6

In [56]:
# Selecione a primeira linha do último array criado
arr9[0]

array([6, 3, 7])

In [61]:
# Selecione do primeiro até o quarto elemento da primeira linha do último array criado
arr9[-1,0:5]

array([7, 2, 5])

In [63]:
# Crie um novo array usando 'ones' com shape (3, 5)
arr10 = np.ones((3,5))

In [64]:
print(arr10)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
arr10.shape

(3, 5)

In [68]:
# Subtraia o novo array de outro com dados aleatórios e armazene o resultado em uma variável chamada 'matrix'
arr11 = arr3-arr10

In [69]:
print(arr11)

[[[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.  9.]
  [ 5.  6.  7.  8.  9.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 11. 12. 13. 14.]
  [10. 11. 12. 13. 14.]
  [10. 11. 12. 13. 14.]]]


In [71]:
# Encontre a média usando 'np.mean()' do valores no novo array chamado 'matrix'
print(arr11.mean())

7.0


In [72]:
np.mean(arr11)

7.0

In [106]:
# Faça a transposição da 'matrix', usando o método '.T'

arr11_transpose = arr11.transpose()

In [107]:
print(arr11_transpose)

[[[ 0.  5. 10.]
  [ 0.  5. 10.]
  [ 0.  5. 10.]]

 [[ 1.  6. 11.]
  [ 1.  6. 11.]
  [ 1.  6. 11.]]

 [[ 2.  7. 12.]
  [ 2.  7. 12.]
  [ 2.  7. 12.]]

 [[ 3.  8. 13.]
  [ 3.  8. 13.]
  [ 3.  8. 13.]]

 [[ 4.  9. 14.]
  [ 4.  9. 14.]
  [ 4.  9. 14.]]]
